package cc.connectcampus.connect_campus.domain.post.exception

import cc.connectcampus.connect_campus.global.error.exception.ErrorCode
import cc.connectcampus.connect_campus.global.error.exception.InvalidValueException

class PostTitleLengthException: InvalidValueException(ErrorCode.POST_TITLE_LENGTH_INVALID)