package cc.connectcampus.connect_campus.domain.post.exception

import cc.connectcampus.connect_campus.global.error.exception.ErrorCode
import cc.connectcampus.connect_campus.global.error.exception.InvalidValueException

class PostTagInvalidException:InvalidValueException(ErrorCode.POST_TAG_INVALID)